version: 2.1
#ansible-playbook -i inventory main.yml
          
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints: ["a2:5f:fb:7e:ab:32:8f:84:d2:c0:f9:46:4d:45:77:06:f0:a4:40:0f"]
    - run:
        name: Install dependencies
        command: |
          apk add --update ansible #install the dependencies
    - run:
        name: Configure server
        command: |
          ansible-playbook main.yml -i inventory --private-key udacity.pem

workflows:
  my_workflow:
    jobs:
    #- create_infrastructure
    - configure_infrastructure