version: 2.1

jobs:
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints: ["56:0d:f9:b4:67:9d:6c:77:9e:8b:4f:d4:8d:5c:d4:cc"]
    - run:
        name: Install dependencies
        command: |
          apk add --update ansible #install the dependencies
    - run:
        name: Configure server
        command: |
          ansible-playbook -i inventory main2.yml

workflows:
  my_workflow:
    jobs:
    - configure_infrastructure