version: 2.1
#ansible-playbook -i inventory main.yml
          
jobs:
  create_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - run:
            name: Create Cloudformation Stack
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region us-east-1

  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
    - checkout
    - add_ssh_keys:
        fingerprints: ["56:0d:f9:b4:67:9d:6c:77:9e:8b:4f:d4:8d:5c:d4:cc"]
    - run:
        name: Install dependencies
        command: |
          apk add --update ansible #install the dependencies
    - run:
        name: Configure server
        command: |
          ansible-playbook main.yml -i inventory --private-key udacity.pem

workflows:
  my_workflow:
    jobs:
    #- create_infrastructure
    - configure_infrastructure